# Generated by Django 4.1 on 2022-09-01 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='SelNetwork',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
